### ISSUE TITLE
Not able to install jupyterlab system monitor

### ISSUE THREAD

**Issue by RohitR1** [jtpio/jupyterlab-system-monitor#27]
Tried Installing using:
```bash
pip install nbresuse
jupyter labextension install jupyterlab-topbar-extension jupyterlab-system-monitor
```

```bash
$ cat /tmp/jupyterlab-debug-jdumqal8.log

Node v13.13.0

Yarn configuration loaded.
> /opt/conda/bin/npm pack jupyterlab-topbar-extension
npm notice
npm notice 📦  jupyterlab-topbar-extension@0.5.0
npm notice === Tarball Contents ===
npm notice 0     style/index.css
npm notice 2.5kB lib/index.js
npm notice 1.3kB package.json
npm notice 581B  schema/plugin.json
npm notice 136B  README.md
npm notice 290B  lib/index.d.ts
npm notice === Tarball Details ===
npm notice name:          jupyterlab-topbar-extension
npm notice version:       0.5.0
npm notice filename:      jupyterlab-topbar-extension-0.5.0.tgz
npm notice package size:  1.8 kB
npm notice unpacked size: 4.8 kB
npm notice shasum:        812c30e13021b5db8b8b9d365218894b18626542
npm notice integrity:     sha512-dnV0KX/k2Y5CW[...]DTQIqMOwHrMMA==
npm notice total files:   6
npm notice
jupyterlab-topbar-extension-0.5.0.tgz

Node v13.13.0

Yarn configuration loaded.
> /opt/conda/bin/npm pack jupyterlab-system-monitor
npm notice
npm notice 📦  jupyterlab-system-monitor@0.6.0
npm notice === Tarball Contents ===
npm notice 63B   style/index.css
npm notice 1.7kB lib/index.js
npm notice 1.6kB package.json
npm notice 789B  schema/plugin.json
npm notice 307B  lib/index.d.ts
npm notice === Tarball Details ===
npm notice name:          jupyterlab-system-monitor
npm notice version:       0.6.0
npm notice filename:      jupyterlab-system-monitor-0.6.0.tgz
npm notice package size:  1.7 kB
npm notice unpacked size: 4.4 kB
npm notice shasum:        949a4abb12c2c8403566001aa3555a6308cdd047
npm notice integrity:     sha512-MA9XAWdSOFTDW[...]DR85XpOdi2JgQ==
npm notice total files:   5
npm notice
jupyterlab-system-monitor-0.6.0.tgz

Node v13.13.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.52s.

> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /opt/conda/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.90s.

> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
Hash: 6d5d205e449dfc0527afc16c1e191e6ee74c5543a3a9631c63c598ea4d2f
Version: webpack 4.43.0
Child
    Hash: 6d5d205e449dfc0527af
    Time: 378054ms
    Built at: 05/11/2020 3:25:46 PM
     33 assets
    Entrypoint main = vendors~main.1321b65aaef3bbcf6e7e.js vendors~main.1321b65aaef3bbcf6e7e.js.map main.ad0dbf3366b6790a45c1.js main.ad0dbf3366b6790a45c1.js.map
    [3] multi whatwg-fetch ./build/index.out.js 40 bytes {0} [built]
    [31N0] ./node_modules/@jupyterlab/csvviewer-extension/lib/index.js + 5 modules 66.7 KiB {2} [optional] [built]
        |    6 modules
    [5pV8] ./node_modules/@jupyterlab/mathjax2-extension/lib/index.js + 1 modules 4.15 KiB {2} [optional] [built]
        |    2 modules
    [93mg] ./node_modules/@jupyterlab/celltags-extension/lib/index.js + 3 modules 15.7 KiB {2} [optional] [built]
        |    4 modules
    [9fgM] ./build/imports.css 463 bytes {0} [built]
    [ANye] ./build/index.out.js 37.4 KiB {0} [built]
    [J1oh] ./node_modules/jupyterlab_tensorboard/lib/index.js + 4 modules 32.5 KiB {2} [optional] [built]
        |    5 modules
    [KKbn] ./node_modules/@jupyter-widgets/jupyterlab-manager/lib/index.js + 7 modules 34.2 KiB {2} [optional] [built]
        |    8 modules
    [NHPb] ./node_modules/@jupyterlab/console-extension/lib/index.js + 1 modules 22.2 KiB {2} [optional] [built]
        |    2 modules
    [QP8U] ./node_modules/@jupyterlab/fileeditor-extension/lib/index.js + 1 modules 34.7 KiB {2} [optional] [built]
        |    2 modules
    [RMrj] ./node_modules/@jupyterlab/inspector-extension/lib/index.js + 1 modules 8.68 KiB {2} [optional] [built]
        |    2 modules
    [U33M] ./node_modules/@jupyterlab/logconsole-extension/lib/index.js + 5 modules 45.7 KiB {2} [optional] [built]
        |    6 modules
    [VYmV] ./node_modules/@jupyterlab/completer-extension/lib/index.js + 7 modules 62.9 KiB {2} [optional] [built]
        |    8 modules
    [ZPDT] ./node_modules/@jupyterlab/extensionmanager-extension/lib/index.js + 7 modules 57.3 KiB {2} [optional] [built]
        |    8 modules
    [dp0r] ./node_modules/@jupyterlab/git/lib/index.js + 104 modules 434 KiB {2} [optional] [built]
        |    105 modules
        + 3606 hidden modules

    WARNING in ./node_modules/moment/locale/en-SG.js
    There are multiple modules with names that only differ in casing.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Use equal casing. Compare these module identifiers:
    * /opt/conda/share/jupyter/lab/staging/node_modules/moment/locale/en-SG.js
        Used by 2 module(s), i. e.
        /opt/conda/share/jupyter/lab/staging/node_modules/moment/locale sync /^\.\/.*$/
    * /opt/conda/share/jupyter/lab/staging/node_modules/moment/locale/en-sg.js
        Used by 2 module(s), i. e.
        /opt/conda/share/jupyter/lab/staging/node_modules/moment/locale sync /^\.\/.*$/
     @ ./node_modules/moment/locale/en-SG.js
     @ ./node_modules/moment/locale sync ^\.\/.*$
     @ ./node_modules/moment/moment.js
     @ ./node_modules/kepler.gl/dist/utils/data-utils.js
     @ ./node_modules/kepler.gl/dist/processors/data-processor.js
     @ ./node_modules/kepler.gl/dist/processors/index.js
     @ ./node_modules/kepler.gl/processors.js
     @ ./node_modules/keplergl-jupyter/babel/keplergl/utils.js
     @ ./node_modules/keplergl-jupyter/babel/keplergl/kepler.gl.js
     @ ./node_modules/keplergl-jupyter/babel/keplergl-plugin.js
     @ ./node_modules/keplergl-jupyter/babel/index.js
     @ ./node_modules/keplergl-jupyter/babel/labplugin.js
     @ ./build/index.out.js
     @ multi whatwg-fetch ./build/index.out.js

    ERROR in vendors~main.1321b65aaef3bbcf6e7e.js from Terser
    Error: Call retries were exceeded
        at ChildProcessWorker.initialize (/opt/conda/share/jupyter/lab/staging/node_modules/jest-worker/build/workers/ChildProcessWorker.js:191:21)
        at ChildProcessWorker._onExit (/opt/conda/share/jupyter/lab/staging/node_modules/jest-worker/build/workers/ChildProcessWorker.js:268:12)
        at ChildProcess.emit (events.js:315:20)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    Child html-webpack-plugin for "index.html":
         1 asset
        Entrypoint undefined = index.html
        [KTNU] ./node_modules/html-loader!./templates/partial.html 703 bytes {0} [built]
        [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
        [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.27 KiB {0} [built]
        [yLpj] (webpack)/buildin/global.js 472 bytes {0} [built]
            + 1 hidden module
Child
    Hash: c16c1e191e6ee74c5543
    Time: 7509ms
    Built at: 05/11/2020 3:19:36 PM
        Asset       Size  Chunks             Chunk Names
    index.css   15.7 KiB       0  [emitted]  index
     index.js  932 bytes       0  [emitted]  index
    Entrypoint index = index.css index.js
       3 modules
    Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/@jupyterlab/theme-dark-extension/style/index.css:
        Entrypoint mini-css-extract-plugin = *
           3 modules
Child
    Hash: a3a9631c63c598ea4d2f
    Time: 7501ms
    Built at: 05/11/2020 3:19:36 PM
        Asset       Size  Chunks             Chunk Names
    index.css   14.7 KiB       0  [emitted]  index
     index.js  932 bytes       0  [emitted]  index
    Entrypoint index = index.css index.js
       3 modules
    Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/@jupyterlab/theme-light-extension/style/index.css:
        Entrypoint mini-css-extract-plugin = *
           3 modules
child_process.js:632
    throw err;
    ^

Error: Command failed: /opt/conda/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/opt/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 3543,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```

**Comment by jtpio** [comment]
@RohitR1 would it be possible to try in a new conda environment?

Just tested locally and the extensions are installed correctly with the latest JupyterLab (2.1.2).

**Comment by nicdelillo** [comment]
Hi @jtpio , I installed it successfully, but it does not look like it is working on the latest MacOS Catalina 10.15.5 . Have you had such a Issue? All looks fine and enabled. Just the top bar and the MEM/CPU usage are not shown

**Comment by jtpio** [comment]
@nicdelillo which version of nbresuse do you have? (it should be 0.3.3)

**Comment by nicdelillo** [comment]
@jtpio  thanks, I am running 0.3.4 . Is this incompatible ? I will install the 0.3.3 if so

**Comment by jtpio** [comment]
@nicdelillo no problem, thanks for checking!

Otherwise yes, 0.3.4 has a breaking change (https://github.com/yuvipanda/nbresuse/issues/36 for more context).

**Comment by jtpio** [comment]
A new version of nbresuse (0.3.5) was released to fix the backward compatibility issues.

Closing as answered, but feel free to comment here or open a new issues to discuss more.
